default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: al_hadika_development

test:
  <<: *default
  database: al_hadika_test

production:
  primary:
    <<: *default
  cache:
    <<: *default
    database: al_hadika_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: al_hadika_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: al_hadika_cable
    migrations_paths: db/cable_migrate
